pull_request_rules:
  - name: merge successful vercel deployments
    conditions:
      - check-success=Vercel
      - base=main
      - label=dependencies
    actions:
      merge:
        method: merge
